"""Run-event reference-spec conformance tests (Phase 3 slice #14).

Validates the good/bad fixture tree under `runtime/fixtures/run-event-v0.1/`
and `assurance/fixtures/canonical_cli/` against the run-event envelope schema
and the 33 event payload schemas. Structure mirrors
`assurance/tests/test_p0_contracts.py` (dict mapping + subTest + iter_errors).

Fixtures are generated by `scripts/generate_run_event_fixtures.py`; the
check_repository gate carries the same mappings plus a completeness
assertion that every fixture file is mapped.
"""

from __future__ import annotations

import json
from pathlib import Path
import unittest

from jsonschema import Draft202012Validator, FormatChecker


ROOT = Path(__file__).resolve().parents[2]
RUNTIME = ROOT / "runtime"
ASSURANCE = ROOT / "assurance"
FIXTURE_ROOT = RUNTIME / "fixtures" / "run-event-v0.1"
PAYLOAD_DIR = FIXTURE_ROOT / "payloads"
ENVELOPE_DIR = FIXTURE_ROOT / "envelope"
CANONICAL_CLI_DIR = ASSURANCE / "fixtures" / "canonical_cli"

RUN_EVENT_SCHEMA = RUNTIME / "run-event-v0.1.schema.json"

# Single registry source (slice #17): the cross-validator's registry — three
# dual-track slugs point at the runtime/ Rust-track files; the assurance/
# twins remain the orientation-track shapes.
from assurance.run_event_journal_validation import (  # noqa: E402
    PAYLOAD_SCHEMA_BY_EVENT_TYPE as _PAYLOAD_SCHEMAS,
)

# Slugs that legitimately exist in BOTH runtime/ (Rust track) and assurance/
# (orientation track) — the registered dual-track collision (slice #17).
DUAL_TRACK_SLUGS = {"orientation-checkpoint", "tool-availability-check", "runtime-stagnation-guard"}

PAYLOAD_POSITIVE_CONTRACTS: dict[Path, Path] = {
    PAYLOAD_DIR / f"{slug}.minimal.valid.json": schema
    for slug, schema in _PAYLOAD_SCHEMAS.values()
}

PAYLOAD_NEGATIVE_CONTRACTS: dict[Path, Path] = {
    PAYLOAD_DIR / f"{slug}.constraint.invalid.json": schema
    for slug, schema in _PAYLOAD_SCHEMAS.values()
}

ENVELOPE_POSITIVE_CONTRACTS: dict[Path, Path] = {
    ENVELOPE_DIR / f"{slug}.valid.json": RUN_EVENT_SCHEMA
    for slug, _ in _PAYLOAD_SCHEMAS.values()
}
ENVELOPE_POSITIVE_CONTRACTS[ENVELOPE_DIR / "chained-run-finished.valid.json"] = (
    RUN_EVENT_SCHEMA
)

ENVELOPE_NEGATIVE_CONTRACTS: dict[Path, Path] = {
    ENVELOPE_DIR / name: RUN_EVENT_SCHEMA
    for name in (
        "bad-schema-version.invalid.json",
        "bad-run-id.invalid.json",
        "bad-event-id.invalid.json",
        "missing-required-payload-schema.invalid.json",
        "negative-sequence.invalid.json",
        "bad-sha256-pattern.invalid.json",
        "unknown-event-type.invalid.json",
        "seq0-non-null-previous.invalid.json",
        "seq1-null-previous.invalid.json",
        "bad-redaction.invalid.json",
        "non-object-payload.invalid.json",
        "additional-properties.invalid.json",
        "missing-timestamp.invalid.json",
    )
}

CANONICAL_CLI_POSITIVE_CONTRACTS: dict[Path, Path] = {
    CANONICAL_CLI_DIR / f"{name}.minimal.valid.json": (
        ASSURANCE / f"{name}-v0.1.schema.json"
    )
    for name in (
        "canonical-cli-preflight",
        "canonical-cli-run-started",
        "canonical-cli-fake-model-request",
        "canonical-cli-real-model-request",
        "canonical-cli-fake-model-output",
        "canonical-cli-real-model-output",
        "canonical-cli-terminal",
    )
}


def load_json(path: Path) -> object:
    return json.loads(path.read_text(encoding="utf-8"))


def errors_for(instance_path: Path, schema_path: Path) -> list[str]:
    validator = Draft202012Validator(
        load_json(schema_path), format_checker=FormatChecker()
    )
    return [error.message for error in validator.iter_errors(load_json(instance_path))]


class RunEventPayloadContractTests(unittest.TestCase):
    def test_payload_positive_contracts_validate(self) -> None:
        for instance_path, schema_path in PAYLOAD_POSITIVE_CONTRACTS.items():
            with self.subTest(instance=instance_path.name):
                self.assertEqual(errors_for(instance_path, schema_path), [])

    def test_payload_negative_contracts_fail_closed(self) -> None:
        for instance_path, schema_path in PAYLOAD_NEGATIVE_CONTRACTS.items():
            with self.subTest(instance=instance_path.name):
                self.assertTrue(errors_for(instance_path, schema_path))

    def test_payload_schema_file_convention(self) -> None:
        """The `*-event-payload-v0.1.schema.json` set has no orphans or gaps;
        the three dual-track slugs must exist in BOTH runtime/ and assurance/
        (registered collision), every other slug in exactly one directory."""
        for event_type, (slug, schema_path) in _PAYLOAD_SCHEMAS.items():
            with self.subTest(event_type=event_type):
                self.assertTrue(schema_path.is_file(), f"missing schema {schema_path}")
        runtime_names = {path.name for path in RUNTIME.glob("*-event-payload-v0.1.schema.json")}
        assurance_names = {path.name for path in ASSURANCE.glob("*-event-payload-v0.1.schema.json")}
        expected = {
            f"{slug}-event-payload-v0.1.schema.json" for slug, _ in _PAYLOAD_SCHEMAS.values()
        }
        self.assertEqual(runtime_names | assurance_names, expected)
        for slug, _ in _PAYLOAD_SCHEMAS.values():
            name = f"{slug}-event-payload-v0.1.schema.json"
            dirs = [
                directory
                for directory, names in (
                    ("runtime", runtime_names),
                    ("assurance", assurance_names),
                )
                if name in names
            ]
            if slug in DUAL_TRACK_SLUGS:
                self.assertEqual(
                    dirs, ["runtime", "assurance"],
                    f"dual-track slug must exist in both dirs: {slug}",
                )
            else:
                self.assertEqual(
                    len(dirs), 1, f"slug must exist in exactly one dir: {slug}"
                )


class RunEventEnvelopeContractTests(unittest.TestCase):
    def test_envelope_samples_validate(self) -> None:
        for instance_path, schema_path in ENVELOPE_POSITIVE_CONTRACTS.items():
            with self.subTest(instance=instance_path.name):
                self.assertEqual(errors_for(instance_path, schema_path), [])

    def test_envelope_negative_samples_fail_closed(self) -> None:
        for instance_path, schema_path in ENVELOPE_NEGATIVE_CONTRACTS.items():
            with self.subTest(instance=instance_path.name):
                self.assertTrue(errors_for(instance_path, schema_path))

    def test_all_34_event_types_covered(self) -> None:
        """The good envelope fixtures cover exactly the run-event enum."""
        schema = load_json(RUN_EVENT_SCHEMA)
        enum_events = set(schema["properties"]["event_type"]["enum"])
        fixture_events = {
            load_json(path)["event_type"]
            for path, _ in ENVELOPE_POSITIVE_CONTRACTS.items()
            if path.name != "chained-run-finished.valid.json"
        }
        self.assertEqual(fixture_events, enum_events)
        self.assertEqual(len(enum_events), 34)


class CanonicalCliPayloadContractTests(unittest.TestCase):
    def test_canonical_cli_positive_contracts_validate(self) -> None:
        for instance_path, schema_path in CANONICAL_CLI_POSITIVE_CONTRACTS.items():
            with self.subTest(instance=instance_path.name):
                self.assertEqual(errors_for(instance_path, schema_path), [])


if __name__ == "__main__":
    unittest.main()
