"""Run-event reference-spec conformance tests (Phase 3 slice #14).

Validates the good/bad fixture tree under `runtime/fixtures/run-event-v0.1/`
and `assurance/fixtures/canonical_cli/` against the run-event envelope schema
and the 33 event payload schemas. Structure mirrors
`assurance/tests/test_p0_contracts.py` (dict mapping + subTest + iter_errors).

Fixtures are generated by `scripts/generate_run_event_fixtures.py`; the
check_repository gate carries the same mappings plus a completeness
assertion that every fixture file is mapped.
"""

from __future__ import annotations

import json
from pathlib import Path
import unittest

from jsonschema import Draft202012Validator, FormatChecker


ROOT = Path(__file__).resolve().parents[2]
RUNTIME = ROOT / "runtime"
ASSURANCE = ROOT / "assurance"
FIXTURE_ROOT = RUNTIME / "fixtures" / "run-event-v0.1"
PAYLOAD_DIR = FIXTURE_ROOT / "payloads"
ENVELOPE_DIR = FIXTURE_ROOT / "envelope"
CANONICAL_CLI_DIR = ASSURANCE / "fixtures" / "canonical_cli"

RUN_EVENT_SCHEMA = RUNTIME / "run-event-v0.1.schema.json"

# event_type -> (slug, payload schema file). The four assurance/ schemas are
# the pre-existing assurance-track shapes; everything else lives in runtime/.
_PAYLOAD_SCHEMAS: dict[str, tuple[str, Path]] = {
    "run_preflight": ("run-preflight", RUNTIME / "run-preflight-event-payload-v0.1.schema.json"),
    "run_started": ("run-started", RUNTIME / "run-started-event-payload-v0.1.schema.json"),
    "prompt_submitted": ("prompt-submitted", RUNTIME / "prompt-submitted-event-payload-v0.1.schema.json"),
    "model_request": ("model-request", RUNTIME / "model-request-event-payload-v0.1.schema.json"),
    "model_response_received": ("model-response-received", RUNTIME / "model-response-received-event-payload-v0.1.schema.json"),
    "model_output": ("model-output", RUNTIME / "model-output-event-payload-v0.1.schema.json"),
    "acp_initialize": ("acp-initialize", RUNTIME / "acp-initialize-event-payload-v0.1.schema.json"),
    "acp_session_created": ("acp-session-created", RUNTIME / "acp-session-created-event-payload-v0.1.schema.json"),
    "tool_proposal": ("tool-proposal", RUNTIME / "tool-proposal-event-payload-v0.1.schema.json"),
    "permission_requested": ("permission-requested", RUNTIME / "permission-requested-event-payload-v0.1.schema.json"),
    "permission_decision": ("permission-decision", RUNTIME / "permission-decision-event-payload-v0.1.schema.json"),
    "tool_started": ("tool-started", RUNTIME / "tool-started-event-payload-v0.1.schema.json"),
    "tool_completed": ("tool-completed", RUNTIME / "tool-completed-event-payload-v0.1.schema.json"),
    "orientation_checkpoint": ("orientation-checkpoint", ASSURANCE / "orientation-checkpoint-event-payload-v0.1.schema.json"),
    "runtime_stagnation_guard": ("runtime-stagnation-guard", ASSURANCE / "runtime-stagnation-guard-event-payload-v0.1.schema.json"),
    "tool_availability_check": ("tool-availability-check", ASSURANCE / "tool-availability-check-event-payload-v0.1.schema.json"),
    "tool_belief_stagnation": ("tool-belief-stagnation", ASSURANCE / "tool-belief-stagnation-event-payload-v0.1.schema.json"),
    "instruction_provenance_gate": ("instruction-provenance-gate", RUNTIME / "instruction-provenance-gate-event-payload-v0.1.schema.json"),
    "gate_decision": ("gate-decision", RUNTIME / "gate-decision-event-payload-v0.1.schema.json"),
    "neutral_inquiry": ("neutral-inquiry", RUNTIME / "neutral-inquiry-event-payload-v0.1.schema.json"),
    "counterexample_gate": ("counterexample-gate", RUNTIME / "counterexample-gate-event-payload-v0.1.schema.json"),
    "retrieval_completion_check": ("retrieval-completion-check", RUNTIME / "retrieval-completion-check-event-payload-v0.1.schema.json"),
    "snapshot_created": ("snapshot-created", RUNTIME / "snapshot-created-event-payload-v0.1.schema.json"),
    "snapshot_restored": ("snapshot-restored", RUNTIME / "snapshot-restored-event-payload-v0.1.schema.json"),
    "artifact_registered": ("artifact-registered", RUNTIME / "artifact-registered-event-payload-v0.1.schema.json"),
    "plan_proposed": ("plan-proposed", RUNTIME / "plan-proposed-event-payload-v0.1.schema.json"),
    "plan_approved": ("plan-approved", RUNTIME / "plan-approved-event-payload-v0.1.schema.json"),
    "plan_rejected": ("plan-rejected", RUNTIME / "plan-rejected-event-payload-v0.1.schema.json"),
    "action_approved": ("action-approved", RUNTIME / "action-approved-event-payload-v0.1.schema.json"),
    "run_finished": ("run-finished", RUNTIME / "run-finished-event-payload-v0.1.schema.json"),
    "run_failed": ("run-failed", RUNTIME / "run-failed-event-payload-v0.1.schema.json"),
    "run_cancelled": ("run-cancelled", RUNTIME / "run-cancelled-event-payload-v0.1.schema.json"),
    "run_invalidated": ("run-invalidated", RUNTIME / "run-invalidated-event-payload-v0.1.schema.json"),
}

PAYLOAD_POSITIVE_CONTRACTS: dict[Path, Path] = {
    PAYLOAD_DIR / f"{slug}.minimal.valid.json": schema
    for slug, schema in _PAYLOAD_SCHEMAS.values()
}

PAYLOAD_NEGATIVE_CONTRACTS: dict[Path, Path] = {
    PAYLOAD_DIR / f"{slug}.constraint.invalid.json": schema
    for slug, schema in _PAYLOAD_SCHEMAS.values()
}

ENVELOPE_POSITIVE_CONTRACTS: dict[Path, Path] = {
    ENVELOPE_DIR / f"{slug}.valid.json": RUN_EVENT_SCHEMA
    for slug, _ in _PAYLOAD_SCHEMAS.values()
}
ENVELOPE_POSITIVE_CONTRACTS[ENVELOPE_DIR / "chained-run-finished.valid.json"] = (
    RUN_EVENT_SCHEMA
)

ENVELOPE_NEGATIVE_CONTRACTS: dict[Path, Path] = {
    ENVELOPE_DIR / name: RUN_EVENT_SCHEMA
    for name in (
        "bad-schema-version.invalid.json",
        "bad-run-id.invalid.json",
        "bad-event-id.invalid.json",
        "missing-required-payload-schema.invalid.json",
        "negative-sequence.invalid.json",
        "bad-sha256-pattern.invalid.json",
        "unknown-event-type.invalid.json",
        "seq0-non-null-previous.invalid.json",
        "seq1-null-previous.invalid.json",
        "bad-redaction.invalid.json",
        "non-object-payload.invalid.json",
        "additional-properties.invalid.json",
        "missing-timestamp.invalid.json",
    )
}

CANONICAL_CLI_POSITIVE_CONTRACTS: dict[Path, Path] = {
    CANONICAL_CLI_DIR / f"{name}.minimal.valid.json": (
        ASSURANCE / f"{name}-v0.1.schema.json"
    )
    for name in (
        "canonical-cli-preflight",
        "canonical-cli-run-started",
        "canonical-cli-fake-model-request",
        "canonical-cli-real-model-request",
        "canonical-cli-fake-model-output",
        "canonical-cli-real-model-output",
        "canonical-cli-terminal",
    )
}


def load_json(path: Path) -> object:
    return json.loads(path.read_text(encoding="utf-8"))


def errors_for(instance_path: Path, schema_path: Path) -> list[str]:
    validator = Draft202012Validator(
        load_json(schema_path), format_checker=FormatChecker()
    )
    return [error.message for error in validator.iter_errors(load_json(instance_path))]


class RunEventPayloadContractTests(unittest.TestCase):
    def test_payload_positive_contracts_validate(self) -> None:
        for instance_path, schema_path in PAYLOAD_POSITIVE_CONTRACTS.items():
            with self.subTest(instance=instance_path.name):
                self.assertEqual(errors_for(instance_path, schema_path), [])

    def test_payload_negative_contracts_fail_closed(self) -> None:
        for instance_path, schema_path in PAYLOAD_NEGATIVE_CONTRACTS.items():
            with self.subTest(instance=instance_path.name):
                self.assertTrue(errors_for(instance_path, schema_path))

    def test_payload_schema_file_convention(self) -> None:
        """Every event type maps to exactly one payload schema file and the
        `*-event-payload-v0.1.schema.json` set has no orphans or gaps."""
        for event_type, (slug, schema_path) in _PAYLOAD_SCHEMAS.items():
            with self.subTest(event_type=event_type):
                self.assertTrue(schema_path.is_file(), f"missing schema {schema_path}")
        actual = {
            path.name
            for path in [
                *RUNTIME.glob("*-event-payload-v0.1.schema.json"),
                *ASSURANCE.glob("*-event-payload-v0.1.schema.json"),
            ]
        }
        expected = {
            f"{slug}-event-payload-v0.1.schema.json" for slug, _ in _PAYLOAD_SCHEMAS.values()
        }
        self.assertEqual(actual, expected)


class RunEventEnvelopeContractTests(unittest.TestCase):
    def test_envelope_samples_validate(self) -> None:
        for instance_path, schema_path in ENVELOPE_POSITIVE_CONTRACTS.items():
            with self.subTest(instance=instance_path.name):
                self.assertEqual(errors_for(instance_path, schema_path), [])

    def test_envelope_negative_samples_fail_closed(self) -> None:
        for instance_path, schema_path in ENVELOPE_NEGATIVE_CONTRACTS.items():
            with self.subTest(instance=instance_path.name):
                self.assertTrue(errors_for(instance_path, schema_path))

    def test_all_33_event_types_covered(self) -> None:
        """The good envelope fixtures cover exactly the run-event enum."""
        schema = load_json(RUN_EVENT_SCHEMA)
        enum_events = set(schema["properties"]["event_type"]["enum"])
        fixture_events = {
            load_json(path)["event_type"]
            for path, _ in ENVELOPE_POSITIVE_CONTRACTS.items()
            if path.name != "chained-run-finished.valid.json"
        }
        self.assertEqual(fixture_events, enum_events)
        self.assertEqual(len(enum_events), 33)


class CanonicalCliPayloadContractTests(unittest.TestCase):
    def test_canonical_cli_positive_contracts_validate(self) -> None:
        for instance_path, schema_path in CANONICAL_CLI_POSITIVE_CONTRACTS.items():
            with self.subTest(instance=instance_path.name):
                self.assertEqual(errors_for(instance_path, schema_path), [])


if __name__ == "__main__":
    unittest.main()
