"""Run-event reference-spec conformance tests (Phase 3 slice #14).

Validates the good/bad fixture tree under `runtime/fixtures/run-event-v0.1/`,
`runtime/fixtures/run-event-v0.2/` and `assurance/fixtures/canonical_cli/`
against the run-event envelope schemas and the event payload schemas.
Structure mirrors `assurance/tests/test_p0_contracts.py` (dict mapping +
subTest + iter_errors).

Phase B v0.2 (ADR-0010 §11.2): the v0.2 tree covers the five v0.2 mechanism
events (payload) and every event in the v0.2 envelope enum. The v0.2 payload
events reuse the v0.1 payload schema files for unchanged shapes.

Fixtures are generated by `scripts/generate_run_event_fixtures.py`; the
check_repository gate carries the same mappings plus a completeness
assertion that every fixture file is mapped.
"""

from __future__ import annotations

import json
from pathlib import Path
import unittest

from jsonschema import Draft202012Validator, FormatChecker


ROOT = Path(__file__).resolve().parents[2]
RUNTIME = ROOT / "runtime"
ASSURANCE = ROOT / "assurance"
FIXTURE_ROOT = RUNTIME / "fixtures" / "run-event-v0.1"
PAYLOAD_DIR = FIXTURE_ROOT / "payloads"
ENVELOPE_DIR = FIXTURE_ROOT / "envelope"
CANONICAL_CLI_DIR = ASSURANCE / "fixtures" / "canonical_cli"

RUN_EVENT_SCHEMA = RUNTIME / "run-event-v0.1.schema.json"
RUN_EVENT_SCHEMA_V02 = RUNTIME / "run-event-v0.2.schema.json"
FIXTURE_ROOT_V02 = RUNTIME / "fixtures" / "run-event-v0.2"
PAYLOAD_DIR_V02 = FIXTURE_ROOT_V02 / "payloads"
ENVELOPE_DIR_V02 = FIXTURE_ROOT_V02 / "envelope"

# Single registry source (slice #17): the cross-validator's registry — three
# dual-track slugs point at the runtime/ Rust-track files; the assurance/
# twins remain the orientation-track shapes.
from assurance.run_event_journal_validation import (  # noqa: E402
    PAYLOAD_SCHEMA_BY_EVENT_TYPE as _PAYLOAD_SCHEMAS,
    PAYLOAD_SCHEMA_BY_EVENT_TYPE_V02 as _PAYLOAD_SCHEMAS_V02,
)

# Slugs that legitimately exist in BOTH runtime/ (Rust track) and assurance/
# (orientation track) — the registered dual-track collision (slice #17).
DUAL_TRACK_SLUGS = {"orientation-checkpoint", "tool-availability-check", "runtime-stagnation-guard"}

PAYLOAD_POSITIVE_CONTRACTS: dict[Path, Path] = {
    PAYLOAD_DIR / f"{slug}.minimal.valid.json": schema
    for slug, schema in _PAYLOAD_SCHEMAS.values()
}

PAYLOAD_NEGATIVE_CONTRACTS: dict[Path, Path] = {
    PAYLOAD_DIR / f"{slug}.constraint.invalid.json": schema
    for slug, schema in _PAYLOAD_SCHEMAS.values()
}

ENVELOPE_POSITIVE_CONTRACTS: dict[Path, Path] = {
    ENVELOPE_DIR / f"{slug}.valid.json": RUN_EVENT_SCHEMA
    for slug, _ in _PAYLOAD_SCHEMAS.values()
}
ENVELOPE_POSITIVE_CONTRACTS[ENVELOPE_DIR / "chained-run-finished.valid.json"] = (
    RUN_EVENT_SCHEMA
)

ENVELOPE_NEGATIVE_CONTRACTS: dict[Path, Path] = {
    ENVELOPE_DIR / name: RUN_EVENT_SCHEMA
    for name in (
        "bad-schema-version.invalid.json",
        "bad-run-id.invalid.json",
        "bad-event-id.invalid.json",
        "missing-required-payload-schema.invalid.json",
        "negative-sequence.invalid.json",
        "bad-sha256-pattern.invalid.json",
        "unknown-event-type.invalid.json",
        "seq0-non-null-previous.invalid.json",
        "seq1-null-previous.invalid.json",
        "bad-redaction.invalid.json",
        "non-object-payload.invalid.json",
        "additional-properties.invalid.json",
        "missing-timestamp.invalid.json",
    )
}

CANONICAL_CLI_POSITIVE_CONTRACTS: dict[Path, Path] = {
    CANONICAL_CLI_DIR / f"{name}.minimal.valid.json": (
        ASSURANCE / f"{name}-v0.1.schema.json"
    )
    for name in (
        "canonical-cli-preflight",
        "canonical-cli-run-started",
        "canonical-cli-fake-model-request",
        "canonical-cli-real-model-request",
        "canonical-cli-fake-model-output",
        "canonical-cli-real-model-output",
        "canonical-cli-terminal",
    )
}


def load_json(path: Path) -> object:
    return json.loads(path.read_text(encoding="utf-8"))


def errors_for(instance_path: Path, schema_path: Path) -> list[str]:
    validator = Draft202012Validator(
        load_json(schema_path), format_checker=FormatChecker()
    )
    return [error.message for error in validator.iter_errors(load_json(instance_path))]


class RunEventPayloadContractTests(unittest.TestCase):
    def test_payload_positive_contracts_validate(self) -> None:
        for instance_path, schema_path in PAYLOAD_POSITIVE_CONTRACTS.items():
            with self.subTest(instance=instance_path.name):
                self.assertEqual(errors_for(instance_path, schema_path), [])

    def test_payload_negative_contracts_fail_closed(self) -> None:
        for instance_path, schema_path in PAYLOAD_NEGATIVE_CONTRACTS.items():
            with self.subTest(instance=instance_path.name):
                self.assertTrue(errors_for(instance_path, schema_path))

    def test_payload_schema_file_convention(self) -> None:
        """The `*-event-payload-v0.1.schema.json` set has no orphans or gaps;
        the three dual-track slugs must exist in BOTH runtime/ and assurance/
        (registered collision), every other slug in exactly one directory."""
        for event_type, (slug, schema_path) in _PAYLOAD_SCHEMAS.items():
            with self.subTest(event_type=event_type):
                self.assertTrue(schema_path.is_file(), f"missing schema {schema_path}")
        runtime_names = {path.name for path in RUNTIME.glob("*-event-payload-v0.1.schema.json")}
        assurance_names = {path.name for path in ASSURANCE.glob("*-event-payload-v0.1.schema.json")}
        expected = {
            f"{slug}-event-payload-v0.1.schema.json" for slug, _ in _PAYLOAD_SCHEMAS.values()
        }
        self.assertEqual(runtime_names | assurance_names, expected)
        for slug, _ in _PAYLOAD_SCHEMAS.values():
            name = f"{slug}-event-payload-v0.1.schema.json"
            dirs = [
                directory
                for directory, names in (
                    ("runtime", runtime_names),
                    ("assurance", assurance_names),
                )
                if name in names
            ]
            if slug in DUAL_TRACK_SLUGS:
                self.assertEqual(
                    dirs, ["runtime", "assurance"],
                    f"dual-track slug must exist in both dirs: {slug}",
                )
            else:
                self.assertEqual(
                    len(dirs), 1, f"slug must exist in exactly one dir: {slug}"
                )


class RunEventEnvelopeContractTests(unittest.TestCase):
    def test_envelope_samples_validate(self) -> None:
        for instance_path, schema_path in ENVELOPE_POSITIVE_CONTRACTS.items():
            with self.subTest(instance=instance_path.name):
                self.assertEqual(errors_for(instance_path, schema_path), [])

    def test_envelope_negative_samples_fail_closed(self) -> None:
        for instance_path, schema_path in ENVELOPE_NEGATIVE_CONTRACTS.items():
            with self.subTest(instance=instance_path.name):
                self.assertTrue(errors_for(instance_path, schema_path))

    def test_all_34_event_types_covered(self) -> None:
        """The good envelope fixtures cover exactly the run-event enum."""
        schema = load_json(RUN_EVENT_SCHEMA)
        enum_events = set(schema["properties"]["event_type"]["enum"])
        fixture_events = {
            load_json(path)["event_type"]
            for path, _ in ENVELOPE_POSITIVE_CONTRACTS.items()
            if path.name != "chained-run-finished.valid.json"
        }
        self.assertEqual(fixture_events, enum_events)
        self.assertEqual(len(enum_events), 34)


PAYLOAD_POSITIVE_CONTRACTS_V02: dict[Path, Path] = {
    PAYLOAD_DIR_V02 / f"{slug}.minimal.valid.json": schema
    for slug, schema in _PAYLOAD_SCHEMAS_V02.values()
}

PAYLOAD_NEGATIVE_CONTRACTS_V02: dict[Path, Path] = {
    PAYLOAD_DIR_V02 / f"{slug}.constraint.invalid.json": schema
    for slug, schema in _PAYLOAD_SCHEMAS_V02.values()
}

# v0.2 envelope fixture filenames: the five v0.2-payload slugs plus the v0.1
# slugs of the events kept on the v0.2 enum (retired events and the
# orientation_checkpoint slot excluded — its v0.2 slug takes over).
_V02_RETIRED_EVENT_TYPES = frozenset({"neutral_inquiry", "retrieval_completion_check"})
_V02_PAYLOAD_SLUGS = {slug for slug, _ in _PAYLOAD_SCHEMAS_V02.values()}
V02_ENUM_SLUGS = [
    *sorted(_V02_PAYLOAD_SLUGS),
    *sorted(
        slug
        for event_type, (slug, _) in _PAYLOAD_SCHEMAS.items()
        if event_type not in _V02_RETIRED_EVENT_TYPES
        and slug not in _V02_PAYLOAD_SLUGS
    ),
]

ENVELOPE_POSITIVE_CONTRACTS_V02: dict[Path, Path] = {
    ENVELOPE_DIR_V02 / f"{slug}.valid.json": RUN_EVENT_SCHEMA_V02
    for slug in V02_ENUM_SLUGS
}
ENVELOPE_POSITIVE_CONTRACTS_V02[ENVELOPE_DIR_V02 / "chained-run-finished.valid.json"] = (
    RUN_EVENT_SCHEMA_V02
)

ENVELOPE_NEGATIVE_CONTRACTS_V02: dict[Path, Path] = {
    ENVELOPE_DIR_V02 / name: RUN_EVENT_SCHEMA_V02
    for name in (
        "bad-schema-version.invalid.json",
        "bad-run-id.invalid.json",
        "bad-event-id.invalid.json",
        "missing-required-payload-schema.invalid.json",
        "negative-sequence.invalid.json",
        "bad-sha256-pattern.invalid.json",
        "unknown-event-type.invalid.json",
        "seq0-non-null-previous.invalid.json",
        "seq1-null-previous.invalid.json",
        "bad-redaction.invalid.json",
        "non-object-payload.invalid.json",
        "additional-properties.invalid.json",
        "missing-timestamp.invalid.json",
        "retired-event-type.invalid.json",
    )
}


class RunEventV02ContractTests(unittest.TestCase):
    """Phase B v0.2 event system (ADR-0010 §11.2/§5.2)."""

    def test_v02_payload_positive_contracts_validate(self) -> None:
        for instance_path, schema_path in PAYLOAD_POSITIVE_CONTRACTS_V02.items():
            with self.subTest(instance=instance_path.name):
                self.assertEqual(errors_for(instance_path, schema_path), [])

    def test_v02_payload_negative_contracts_fail_closed(self) -> None:
        for instance_path, schema_path in PAYLOAD_NEGATIVE_CONTRACTS_V02.items():
            with self.subTest(instance=instance_path.name):
                self.assertTrue(errors_for(instance_path, schema_path))

    def test_v02_envelope_samples_validate(self) -> None:
        for instance_path, schema_path in ENVELOPE_POSITIVE_CONTRACTS_V02.items():
            with self.subTest(instance=instance_path.name):
                self.assertEqual(errors_for(instance_path, schema_path), [])

    def test_v02_envelope_negative_samples_fail_closed(self) -> None:
        for instance_path, schema_path in ENVELOPE_NEGATIVE_CONTRACTS_V02.items():
            with self.subTest(instance=instance_path.name):
                self.assertTrue(errors_for(instance_path, schema_path))

    def test_v02_all_39_event_types_covered(self) -> None:
        """The v0.2 good envelope fixtures cover exactly the v0.2 enum, and
        the retired v0.1 events are absent from it (ADR-0010 §11.2).
        GAP-RETRIEVAL-TOOLS (2026-08-10): 36 → 39 (+retrieval_mode_transition,
        +retrieval_result_committed, +retrieval_activation_restored)."""
        schema = load_json(RUN_EVENT_SCHEMA_V02)
        enum_events = set(schema["properties"]["event_type"]["enum"])
        fixture_events = {
            load_json(path)["event_type"]
            for path, _ in ENVELOPE_POSITIVE_CONTRACTS_V02.items()
            if path.name != "chained-run-finished.valid.json"
        }
        self.assertEqual(fixture_events, enum_events)
        self.assertEqual(len(enum_events), 39)
        self.assertNotIn("neutral_inquiry", enum_events)
        self.assertNotIn("retrieval_completion_check", enum_events)

    def test_v02_payload_schema_file_convention(self) -> None:
        """Every v0.2-payload event maps to a v0.2 schema file in runtime/."""
        for event_type, (slug, schema_path) in _PAYLOAD_SCHEMAS_V02.items():
            with self.subTest(event_type=event_type):
                self.assertTrue(schema_path.is_file(), f"missing schema {schema_path}")
                self.assertEqual(schema_path.name, f"{slug}-event-payload-v0.2.schema.json")

    def test_v02_neutral_inquiry_payloads_are_explicit(self) -> None:
        """§5.1: the two neutral inquiry payloads pin inquiry_family=neutral
        and inquiry_kind to the event type."""
        for event_type in ("orientation_checkpoint", "diagnostic_coverage_checkpoint"):
            with self.subTest(event_type=event_type):
                payload_path = (
                    PAYLOAD_DIR_V02
                    / f"{_PAYLOAD_SCHEMAS_V02[event_type][0]}.minimal.valid.json"
                )
                payload = load_json(payload_path)
                self.assertEqual(payload["inquiry_family"], "neutral")
                self.assertEqual(payload["inquiry_kind"], event_type)


class CanonicalCliPayloadContractTests(unittest.TestCase):
    def test_canonical_cli_positive_contracts_validate(self) -> None:
        for instance_path, schema_path in CANONICAL_CLI_POSITIVE_CONTRACTS.items():
            with self.subTest(instance=instance_path.name):
                self.assertEqual(errors_for(instance_path, schema_path), [])


if __name__ == "__main__":
    unittest.main()
